"""initial schema

Revision ID: 6c1ac6215451
Revises: 
Create Date: 2026-08-25 11:40:47.234193
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6c1ac6215451'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('socials', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('source', sa.Enum('FORM', 'EMAIL', 'DM', 'HUNTER', 'MANUAL', name='leadsource'), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority'), nullable=True),
    sa.Column('brand', sa.Enum('MIDNIGHTSATIN', 'CELESTIAL_NEXUS', 'HEYBUDDY', 'UNASSIGNED', name='brand'), nullable=False),
    sa.Column('enrichment_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ACTIVE', 'DISQUALIFIED', 'ARCHIVED', name='leadstatus'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_email'), ['email'], unique=False)

    op.create_table('journeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('template_set', sa.String(length=128), nullable=False),
    sa.Column('brand', sa.Enum('MIDNIGHTSATIN', 'CELESTIAL_NEXUS', 'HEYBUDDY', 'UNASSIGNED', name='brand'), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'STOPPED', 'COMPLETED', name='journeystatus'), nullable=False),
    sa.Column('stop_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journeys_lead_id'), ['lead_id'], unique=False)

    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.Enum('NEW', 'PROSPECT', 'SCORED', 'ENRICHED', 'CONTACTED', 'REPLIED', 'QUALIFIED', 'WON', 'LOST', name='stage'), nullable=False),
    sa.Column('brand', sa.Enum('MIDNIGHTSATIN', 'CELESTIAL_NEXUS', 'HEYBUDDY', 'UNASSIGNED', name='brand'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_hot', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_stage'), ['stage'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('LEAD_CREATED', 'SCORED', 'BRAND_ROUTED', 'ENRICHED', 'STAGE_CHANGED', 'OUTREACH_DRAFTED', 'MESSAGE_SENT', 'MESSAGE_REPLIED', 'HOT_LEAD_ALERT', 'NOTE', 'SCRAPE', 'ERROR', name='activitytype'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_lead_id'), ['lead_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_lead_id'))

    op.drop_table('activities')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_stage'))

    op.drop_table('opportunities')
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journeys_lead_id'))

    op.drop_table('journeys')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_email'))

    op.drop_table('leads')
    op.drop_table('accounts')
    # ### end Alembic commands ###
